version: '2'

services:
  minio:
    image: minio/minio
    # container_name: minio
    # restart: unless-stopped
    # network_mode: "bridge"
    ports:
      - '9009:9000'
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
    # volumes:
    #   - './minio:/root/.minio'
    #   - '${PWD}:/export'
    command: server /export
